spring:
  application:
    name: kakaotaxi

  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    url: /v3/api-docs
  use-management-port: false

server:
  forward-headers-strategy: framework
